Question 1:  What is Logistic Regression, and how does it differ from Linear Regression?
- Logistic regression and linear regression are both used for prediction.
- logistic regression predicts a categorical outcome while linear regression predicts a continuous numerical outcome

Question 2: Explain the role of the Sigmoid function in Logistic Regression.
- The sigmoid function transforms a model's raw, unbounded output into a probability between 0 and 1, enabling binary classification by mapping this probability to discrete outcomes (0 or 1).

Question 3: What is Regularization in Logistic Regression and why is it needed?
- a technique that prevents overfitting by adding a penalty term to the loss function, which shrinks model coefficients and reduces complexity

Question 4: What are some common evaluation metrics for classification models, and why are they important?
- Accuracy, Precision, Recall (Sensitivity), Specificity, F1-Score, and AUC-ROC
-



In [1]:
#Question 5: Write a Python program that loads a CSV file into a Pandas DataFrame, splits into train/test sets,
#trains a Logistic Regression model, and prints its accuracy.
#(Use Dataset from sklearn package) (Include your Python code and output in the code box below.)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 1)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9666666666666667


In [2]:
#Question 6:  Write a Python program to train a Logistic Regression model using L2 regularization (Ridge) and print the model coefficients and accuracy.
 #(Use Dataset from sklearn package) (Include your Python code and output in the code box below.)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 1)
model = LogisticRegression(penalty='l2', C=1.0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(model.coef_)

Accuracy: 0.9666666666666667
[[-0.43171259  0.82344651 -2.35119244 -0.96938012]
 [ 0.61818491 -0.42815386 -0.20595953 -0.82952283]
 [-0.18647232 -0.39529265  2.55715197  1.79890295]]


In [5]:
#Question 7: Write a Python program to train a Logistic Regression model for multiclass classification using multi_class='ovr' and print the classification report.
 #(Use Dataset from sklearn package) (Include your Python code and output in the code box below.)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_classification
from sklearn.metrics import classification_report
X,y =  make_classification(n_samples=1000, n_features=10, n_redundant=5, n_informative=5, n_classes=3, random_state=1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=1)
model = LogisticRegression(multi_class='ovr')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.76      0.72        99
           1       0.62      0.65      0.64        89
           2       0.76      0.67      0.71       112

    accuracy                           0.69       300
   macro avg       0.69      0.69      0.69       300
weighted avg       0.70      0.69      0.69       300



/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [6]:
#Question 8: Write a Python program to apply GridSearchCV to tune C and penalty hyperparameters for Logistic Regression and print the best parameters and validation accuracy.
 #(Use Dataset from sklearn package) (Include your Python code and output in the code box below.)
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, train_test_split

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

logistic_regression = LogisticRegression(solver='liblinear', max_iter=1000)
param_grid = {
    'C': np.logspace(-4, 4, 10),
    'penalty': ['l1', 'l2']
}

grid_search = GridSearchCV(estimator=logistic_regression, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1, n_jobs=-1)

grid_search.fit(X_train, y_train)
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best validation accuracy: {grid_search.best_score_:.4f}")
best_model = grid_search.best_estimator_
test_accuracy = best_model.score(X_test, y_test)
print(f"Test set accuracy with best parameters: {test_accuracy:.4f}")



Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best parameters: {'C': np.float64(1291.5496650148827), 'penalty': 'l2'}
Best validation accuracy: 0.9626
Test set accuracy with best parameters: 0.9561


In [7]:
#Question 9: Write a Python program to standardize the features before training Logistic Regression and compare the model's accuracy with and without scaling.
 #(Use Dataset from sklearn package) (Include your Python code and output in the code box below.)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 1)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy without scaling: {accuracy}")
model_scaled = LogisticRegression()
model_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = model_scaled.predict(X_test_scaled)
accuracy_scaled = accuracy_score(y_test, y_pred_scaled)
print(f"Accuracy with scaling: {accuracy_scaled}")

Accuracy without scaling: 0.9666666666666667
Accuracy with scaling: 0.9666666666666667


In [8]:
#Question 10: Imagine you are working at an e-commerce company that wants to predict which customers will respond to a marketing campaign.
#Given an imbalanced dataset (only 5% of customers respond), describe the approach you’d take to build a Logistic Regression model —
#including data handling, feature scaling, balancing classes, hyperparameter tuning, and evaluating the model for this real-world business use case.

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
import numpy as np

# 1. Simulate an imbalanced dataset
# In a real scenario, you would load your data from a CSV, database, etc.
np.random.seed(42)
n_samples = 1000
n_features = 10

# Generate features
X = np.random.rand(n_samples, n_features) * 10

# Generate target with 5% positive class
y = np.zeros(n_samples)
positive_indices = np.random.choice(n_samples, int(n_samples * 0.05), replace=False)
y[positive_indices] = 1

# Convert to DataFrame for easier handling
df = pd.DataFrame(X, columns=[f'feature_{i}' for i in range(n_features)])
df['target'] = y

# Separate features (X) and target (y)
X = df.drop('target', axis=1)
y = df['target']

# 2. Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 3. Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Balancing Classes using SMOTE (Synthetic Minority Over-sampling Technique)
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

print(f"Original training class distribution: {np.bincount(y_train.astype(int))}")
print(f"Resampled training class distribution: {np.bincount(y_train_resampled.astype(int))}")

# 5. Hyperparameter Tuning for Logistic Regression
# Define the parameter grid for GridSearchCV
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],  # Inverse of regularization strength
    'solver': ['liblinear', 'lbfgs'], # Algorithm to use in the optimization problem
    'class_weight': [None, 'balanced'] # Handle class imbalance by adjusting weights
}

# Initialize Logistic Regression model
log_reg = LogisticRegression(random_state=42, max_iter=1000)

# Initialize GridSearchCV
grid_search = GridSearchCV(log_reg, param_grid, cv=5, scoring='roc_auc', n_jobs=-1, verbose=1)

# Fit GridSearchCV on the resampled training data
grid_search.fit(X_train_resampled, y_train_resampled)

# Get the best estimator
best_log_reg = grid_search.best_estimator_

print(f"\nBest hyperparameters: {grid_search.best_params_}")

# 6. Model Training and Evaluation
# Make predictions on the scaled test set using the best model
y_pred = best_log_reg.predict(X_test_scaled)
y_pred_proba = best_log_reg.predict_proba(X_test_scaled)[:, 1]

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print(f"ROC AUC Score: {roc_auc_score(y_test, y_pred_proba):.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Original training class distribution: [760  40]
Resampled training class distribution: [760 760]
Fitting 5 folds for each of 24 candidates, totalling 120 fits

Best hyperparameters: {'C': 10, 'class_weight': None, 'solver': 'lbfgs'}

Classification Report:
              precision    recall  f1-score   support

         0.0       0.93      0.55      0.69       190
         1.0       0.02      0.20      0.04        10

    accuracy                           0.54       200
   macro avg       0.48      0.38      0.37       200
weighted avg       0.88      0.54      0.66       200

ROC AUC Score: 0.3263

Confusion Matrix:
[[105  85]
 [  8   2]]
